### ISSUE TITLE
[1.12.2] Enderman rendering problem with Seus shaders

### ISSUE THREAD

**Issue by Zygus42** [Fuzss/betteranimationscollection2#1]
With shader, Without mod:
![2019-08-15_00 39 58](https://user-images.githubusercontent.com/20757445/63039330-a8d05000-bef5-11e9-9e73-dbaf54a26d4b.png)

With shader, With mod:
![2019-08-15_00 40 39](https://user-images.githubusercontent.com/20757445/63039365-b71e6c00-bef5-11e9-8fa2-5f4e20e51147.png)

forge-1.12.2-14.23.5.2838-installer-win
BetterAnimationsCollection2-v1.0.1-1.12.2
OptiFine_1.12.2_HD_U_E3
SEUS-Renewed-1.0.0 (shaderpack)

**Comment by Fuzss** [comment]
Better Animations Collection 2 doesn't change the enderman model in any way that could result in this appearance. I'm guessing it's a bug or incompatibility within Forge or OptiFine. There's nothing I can do about it. If it really bothers you the only thing you can do is to deactivate the enderman animation.
